### ISSUE TITLE
add 64-bit support

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/build-win32#10]
We should (optionally?) make 64-bit Windows binaries. 64-bit nip2 is probably not possible without switching to gtk3, but a 64-bit libvips should be fairly easy.

see https://github.com/jcupitt/libvips/issues/323

**Comment by simonmueller2** [comment]
Yes, this is a greate idea!

**Comment by jcupitt** [comment]
I tried adapting build-win32, but it looks like a 64-bit build is going to be significantly different, so I've started a new project:

https://github.com/jcupitt/build-win64

Progress, if any, will happen there.

**Comment by jcupitt** [comment]
I've made a test 64-bit libvips for Windows:

http://www.vips.ecs.soton.ac.uk/development/

It seems to work, but I've done very little testing. If anyone has time to kick the tyres, that'd be wonderful. See https://github.com/jcupitt/build-win64 for the build scripts.

**Comment by AndreasSchmid1** [comment]
I tested some functions. So far everything is working perfect. Thank you!

**Comment by jcupitt** [comment]
Great! sharp are reporting they they have it working with node.js on 64-bit Windows too, so I think we are done.

There's now an official w64 zip here:

http://www.vips.ecs.soton.ac.uk/supported/current/win32/
