### ISSUE TITLE
Provide Compiled Binaries

### ISSUE THREAD

**Issue by grintor** [jcupitt/build-win32#14]
Hey there.

I am working on a 32 bit windows app that I want to make use of libvips for, so I started my day searching for a compiled 32 bit libvips.dll. The 64 bit ones are readily available, but I never found the 32 bit ones. So I spent the rest of my day struggling to compile one myself.

I couldn't get 8.7 to compile, because it has references to 64-bit only things I think... I have 8.6 compiling now and it is getting further than 8.7 did, so maybe it will succeed. But it would have been a much better day if the 32 bit dll's were just downloadable like the 64 bit ones.

Do you happen to have the 32 bit binaries laying around somewhere? If so, I would really appreciate it if you would post them for download somewhere.

Thank you for your time,
Chris

**Comment by jcupitt** [comment]
Hi Chris, yes, it's a beast to compile on Windows.

We've found it simpler to cross-compile from linux. WSL should work, but docker certainly does. I'd use bionic as a base image.

This thing makes a 32-bit `nip2` exe:

https://github.com/libvips/build-win32

But of course it makes libvips as part of the process. Just run:

```
jhbuild --file=jhbuildrc --moduleset=vips.modules build --nodeps  libvips
```

In the 8.7 subdir. There's a README in there with some notes.

Will you need .lib and .def files too? You'll need to make those separately. The better-maintained build-win64 has some scripts to do this for you.

**Comment by jcupitt** [comment]
Oh, of course you could download nip2 (my 32-bit windows application) and just copy the DLLs out of that, if that's all you need.

https://github.com/libvips/nip2/releases/download/v8.7.0/nip2-8.7.0-setup.zip

**Comment by jcupitt** [comment]
nip2 hasn't been updated for 8.8 yet -- I'm switching to 64 bits and it's still not quite done.

**Comment by grintor** [comment]
Thanks a lot! That really helps.
