### ISSUE TITLE
Patchfile, presumably for replacing perl position, missing

### ISSUE THREAD

**Issue by Jondeen** [jcupitt/build-win32#9]
Hi,

Upon building the 8.0 tree the jhbuild halts on a missing file @/home/jcupitt/[...]/transform.patch. Consecutively, the build fails due to an unlocated perl shebang. I'm guessing the two are related, as ignoring the first + patching the second manually fixes the errs.

**Comment by jcupitt** [comment]
Yes, you should comment out the transform.patch stuff, it's some non-GPL code from a friend I can't distribute. On linux, it's a binary plugin, but on Windows I have to paste it into the sources.
